In [7]:
pip install numpy

180.84s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


  Using cached numpy-2.0.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.0.0-cp312-cp312-macosx_14_0_arm64.whl (5.0 MB)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

One D Array

In [3]:
oneDArray = np.array([1,2,3,4,5])

print(oneDArray)

[1 2 3 4 5]


In [8]:
print(f'Dimension = {oneDArray.ndim}')
print(f'Size = {oneDArray.size}')
print(f'Shape = {oneDArray.shape}')



Dimension = 1
Size = 5
Shape = (5,)



Two D Array

In [24]:
twoDArray = np.array([ [1,2,3] ])
print(twoDArray)

[[1 2 3]]


In [25]:
print(f'Dimension = {twoDArray.ndim}')
print(f'Size = {twoDArray.size}')
print(f'Shape = {twoDArray.shape}')



Dimension = 2
Size = 3
Shape = (1, 3)


In [12]:
twoDArray = np.array([[1,2,3],[4,5,6]])
print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [13]:
print(f'Dimension = {twoDArray.ndim}')
print(f'Size = {twoDArray.size}')
print(f'Shape = {twoDArray.shape}')



Dimension = 2
Size = 6
Shape = (2, 3)


3D Array --- Each elemnet of the outermost array is a 2-D array

In [20]:
threeDArray = np.array([ [[1,2,3],[4,5,6]] ])
print(threeDArray)

[[[1 2 3]
  [4 5 6]]]


In [21]:
print(f'Dimension = {threeDArray.ndim}')
print(f'Size = {threeDArray.size}')
print(f'Shape = {threeDArray.shape}')

Dimension = 3
Size = 6
Shape = (1, 2, 3)


In [22]:
threeDArray = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]  ])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(f'Dimension = {threeDArray.ndim}')
print(f'Size = {threeDArray.size}')
print(f'Shape = {threeDArray.shape}')

Dimension = 3
Size = 12
Shape = (2, 2, 3)


Indexing NumPy Arrays

1-D NumPy Arrays indexing

In [26]:
oneDArray = np.array([0,1,2])
print(oneDArray)

[0 1 2]


In [27]:
print(oneDArray[2])

2


2-D NumPy Arrays indexing

In [28]:
twoDArray = np.array([ [1,2,3] ])
print(twoDArray)

[[1 2 3]]


In [33]:
print(twoDArray[0])

[1 2 3]


In [34]:
print(twoDArray[0,1])


2


In [35]:
twoDArray = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(twoDArray[1])

[4 5 6]


In [37]:
print(twoDArray[2][1])

8


3-D NumPy Arrays indexing

In [38]:
threeDArray = np.array([ [ [1,2,3],[-1,-2,-3] ] ])
print(threeDArray)

[[[ 1  2  3]
  [-1 -2 -3]]]


In [43]:
print(threeDArray[0,1,2])

-3


In [44]:
threeDArray = np.array([ [ [1,2,3],[-1,-2,-3] ] , [ [10,20,30],[-10,-20,-30] ] ])
print(threeDArray)

[[[  1   2   3]
  [ -1  -2  -3]]

 [[ 10  20  30]
  [-10 -20 -30]]]


In [46]:
print(threeDArray[1,0,0])

10


Iterating over NumPy Arrays

In [47]:
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
for i in twoDArray:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [49]:
for i in twoDArray:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [51]:
print(threeDArray)

[[[  1   2   3]
  [ -1  -2  -3]]

 [[ 10  20  30]
  [-10 -20 -30]]]


In [52]:
for i in threeDArray:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 10  20  30]
 [-10 -20 -30]]


In [53]:
for i in threeDArray:
    for j in i:
        print(j)

[1 2 3]
[-1 -2 -3]
[10 20 30]
[-10 -20 -30]


In [54]:
for i in threeDArray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
10
20
30
-10
-20
-30
