In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\heart\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

One D Array

In [3]:
oneDArray = np.array([1,2,3,4,5])

print(oneDArray)

[1 2 3 4 5]


In [4]:
print(f'Dimension = {oneDArray.ndim}')
print(f'Size = {oneDArray.size}')
print(f'Shape = {oneDArray.shape}')



Dimension = 1
Size = 5
Shape = (5,)



Two D Array

In [5]:
twoDArray = np.array([ [1,2,3] ])
print(twoDArray)

[[1 2 3]]


In [6]:
print(f'Dimension = {twoDArray.ndim}')
print(f'Size = {twoDArray.size}')
print(f'Shape = {twoDArray.shape}')



Dimension = 2
Size = 3
Shape = (1, 3)


In [7]:
twoDArray = np.array([[1,2,3],[4,5,6]])
print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [8]:
print(f'Dimension = {twoDArray.ndim}')
print(f'Size = {twoDArray.size}')
print(f'Shape = {twoDArray.shape}')



Dimension = 2
Size = 6
Shape = (2, 3)


3D Array --- Each elemnet of the outermost array is a 2-D array

In [9]:
threeDArray = np.array([ [[1,2,3],[4,5,6]] ])
print(threeDArray)

[[[1 2 3]
  [4 5 6]]]


In [10]:
print(f'Dimension = {threeDArray.ndim}')
print(f'Size = {threeDArray.size}')
print(f'Shape = {threeDArray.shape}')

Dimension = 3
Size = 6
Shape = (1, 2, 3)


In [11]:
threeDArray = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]  ])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(f'Dimension = {threeDArray.ndim}')
print(f'Size = {threeDArray.size}')
print(f'Shape = {threeDArray.shape}')

Dimension = 3
Size = 12
Shape = (2, 2, 3)


Indexing NumPy Arrays

1-D NumPy Arrays indexing

In [13]:
oneDArray = np.array([0,1,2])
print(oneDArray)

[0 1 2]


In [14]:
print(oneDArray[2])

2


2-D NumPy Arrays indexing

In [15]:
twoDArray = np.array([ [1,2,3] ])
print(twoDArray)

[[1 2 3]]


In [16]:
print(twoDArray[0])

[1 2 3]


In [17]:
print(twoDArray[0,1])


2


In [18]:
twoDArray = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(twoDArray[1])

[4 5 6]


In [20]:
print(twoDArray[2][1])

8


3-D NumPy Arrays indexing

In [21]:
threeDArray = np.array([ [ [1,2,3],[-1,-2,-3] ] ])
print(threeDArray)

[[[ 1  2  3]
  [-1 -2 -3]]]


In [22]:
print(threeDArray[0,1,2])

-3


In [23]:
threeDArray = np.array([ [ [1,2,3],[-1,-2,-3] ] , [ [10,20,30],[-10,-20,-30] ] ])
print(threeDArray)

[[[  1   2   3]
  [ -1  -2  -3]]

 [[ 10  20  30]
  [-10 -20 -30]]]


In [24]:
print(threeDArray[1,0,0])

10


Iterating over NumPy Arrays

In [25]:
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
for i in twoDArray:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [27]:
for i in twoDArray:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [28]:
print(threeDArray)

[[[  1   2   3]
  [ -1  -2  -3]]

 [[ 10  20  30]
  [-10 -20 -30]]]


In [29]:
for i in threeDArray:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 10  20  30]
 [-10 -20 -30]]


In [30]:
for i in threeDArray:
    for j in i:
        print(j)

[1 2 3]
[-1 -2 -3]
[10 20 30]
[-10 -20 -30]


In [31]:
for i in threeDArray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
10
20
30
-10
-20
-30
