In [57]:
import numpy as np

zeros Array

In [58]:
zerosArray = np.zeros(10)
print(zerosArray)
print(zerosArray.ndim)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1


In [59]:
zerosArray = np.zeros([1,2])
print(zerosArray)
print(zerosArray.ndim)

[[0. 0.]]
2


In [60]:
zerosArray = np.zeros([1,2,10])
print(zerosArray)
print(zerosArray.ndim)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
3


In [61]:
#for int type of zeros

zerosArray = np.zeros(5).astype(int)
print(zerosArray)

[0 0 0 0 0]


In [62]:
#for int type of zeros

zerosArray = np.zeros([5,1]).astype(int)
print(zerosArray)

[[0]
 [0]
 [0]
 [0]
 [0]]


In [63]:
#for int type of zeros

zerosArray = np.zeros([5,1,2]).astype(int)
print(zerosArray)

[[[0 0]]

 [[0 0]]

 [[0 0]]

 [[0 0]]

 [[0 0]]]


Ones Array

In [64]:
onesArray = np.ones(10).astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [65]:
onesArray = np.ones([2,3]).astype(int)
print(onesArray)

[[1 1 1]
 [1 1 1]]


In [66]:
onesArray = np.ones([2,3,1]).astype(int)
print(onesArray)

[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]


Full array --- To fill the element of our choice

In [67]:
fullArray = np.full(3,2.5)
print(fullArray)

[2.5 2.5 2.5]


In [68]:
fullArray = np.full(5,0)
print(fullArray)

[0 0 0 0 0]


Scalar Operations

Addition and Subtraction


In [69]:
print(fullArray)

print(fullArray + 19)

[0 0 0 0 0]
[19 19 19 19 19]


In [70]:
twoDArray = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray)
print('After Adding 10')
print(twoDArray + 10)

[[1 2 3]
 [4 5 6]]
After Adding 10
[[11 12 13]
 [14 15 16]]


In [71]:
twoDArray = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray)
print('After subtracting  2')
print(twoDArray -2)

[[1 2 3]
 [4 5 6]]
After subtracting  2
[[-1  0  1]
 [ 2  3  4]]


In [72]:
twoDArray = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray)
print('After multiply  2')
print(twoDArray * 2)

[[1 2 3]
 [4 5 6]]
After multiply  2
[[ 2  4  6]
 [ 8 10 12]]


In [73]:
#checking the same on list 
lst1 = [1,2,3]
print(lst1 * 2)

[1, 2, 3, 1, 2, 3]


In [74]:
twoDArray = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray)
print('After division from   2')
print(twoDArray / 2)

[[1 2 3]
 [4 5 6]]
After division from   2
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [75]:
twoDArray = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray)
print('After division from   2')
print(twoDArray // 2)

[[1 2 3]
 [4 5 6]]
After division from   2
[[0 1 1]
 [2 2 3]]


Transposing Numpy Array ----> numpyarray.T

In [76]:
print('Before Transposing')
print(twoDArray)
print('After Transposing')
print(twoDArray.T)

Before Transposing
[[1 2 3]
 [4 5 6]]
After Transposing
[[1 4]
 [2 5]
 [3 6]]


Element Wise Addition

In [77]:
#Addition
twoDArray1 = np.array([ [1,2,3],[4,5,6] ])
twoDArray2 = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray1 + twoDArray2)


[[ 2  4  6]
 [ 8 10 12]]


In [78]:
#Subtraction
twoDArray1 = np.array([ [1,2,3],[4,5,6] ])
twoDArray2 = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray1 - twoDArray2)


[[0 0 0]
 [0 0 0]]


In [79]:
#Multiplication 
twoDArray1 = np.array([ [1,2,3],[4,5,6] ])
twoDArray2 = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray1 * twoDArray2)


[[ 1  4  9]
 [16 25 36]]


In [80]:
#Division to get int value
twoDArray1 = np.array([ [1,2,3],[4,5,6] ])
twoDArray2 = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray1 // twoDArray2)


[[1 1 1]
 [1 1 1]]


In [81]:
#Division to get float value
twoDArray1 = np.array([ [1,2,3],[4,5,6] ])
twoDArray2 = np.array([ [1,2,3],[4,5,6] ])
print(twoDArray1 / twoDArray2)


[[1. 1. 1.]
 [1. 1. 1.]]


Matrix Multiplication ----.matmul

In [82]:
np.matmul(twoDArray1,twoDArray1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Here's a step-by-step example to ensure the dimensions are correct:

Check the shapes of your arrays.
Make sure the number of columns in the first array matches the number of rows in the second array.
Let's say twoDArray1 is a 2x3 matrix. To multiply it with another matrix, the second matrix should be a 3xN matrix.
In above example: its 2*3 vs 2*3 that's why issue


In [83]:
np.matmul(twoDArray1,twoDArray1.T)

array([[14, 32],
       [32, 77]])

In [84]:
# Example 2D array
twoDArray1 = np.array([[1, 2],
                       [3, 4]])

# Matrix multiplication
result = np.matmul(twoDArray1, twoDArray1)

print(result)

[[ 7 10]
 [15 22]]
